include VERSION

ifndef JAVA_HOME
$(warning Set JAVA_HOME environment variable)
endif

JAVA  := "$$JAVA_HOME/bin/java"
JAVAC := "$$JAVA_HOME/bin/javac" 
JAVAH := "$$JAVA_HOME/bin/javah"

TARGET := target
SRC:=src/main/java
OSINFO_CLASS := org.sqlite.util.OSInfo
OSINFO_PROG := lib/org/sqlite/util/OSInfo.class

# Windows uses different path separators
ifeq ($(OS_NAME),Windows)
	sep := ;
else
	sep := :
endif

sqlite := sqlite-$(version)

ifdef JAVA_HOME
jni_h := $(shell find -L "$(JAVA_HOME)" -name jni.h)
ifneq ($(jni_h),)
jni_include := $(shell dirname "$(jni_h)")
endif

jni_md := $(shell find -L "$(JAVA_HOME)" -name jni_md.h)
ifneq ($(jni_md),)
jni_md_include := $(shell dirname "$(jni_md)")
endif
endif

# os=Default is meant to be generic unix/linux

known_targets := Linux-Android-arm Linux-Android-aarch64 Linux-Android-x86 Linux-Android-x86_64 Windows-x86_64 Mac-x86_64 Mac-aarch64
target := $(OS_NAME)-$(OS_ARCH)

ifeq (,$(findstring $(strip $(target)),$(known_targets)))
  target := Default
endif

$(info Will build using target: $(target) (detected os: $(OS_NAME), arch: $(OS_ARCH)))

# cross-compilation toolchain prefix (e.g. "arm-linux-gnueabi-")
CROSS_PREFIX :=

Default_CC        := $(CROSS_PREFIX)gcc
Default_STRIP     := $(CROSS_PREFIX)strip
Default_CCFLAGS   := -I$(JAVA_HOME)/include -Ilib/inc_linux -Os -fPIC -fvisibility=hidden
Default_LINKFLAGS := -shared -static-libgcc -pthread -lm
Default_LIBNAME   := libsqlitejdbc.so
Default_SQLITE_FLAGS  := 

Linux-x86_64_CC        := $(CROSS_PREFIX)gcc
Linux-x86_64_STRIP     := $(CROSS_PREFIX)strip
Linux-x86_64_CCFLAGS   := -Ilib/inc_linux -I$(JAVA_HOME)/include -Os -g -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIC -lm -lc -m64 -fvisibility=hidden
Linux-x86_64_LINKFLAGS := $(Default_LINKFLAGS)
Linux-x86_64_LIBNAME   := libsqlitejdbc.so
Linux-x86_64_SQLITE_FLAGS  := 

Linux-arm_CC          := $(CROSS_PREFIX)gcc
Linux-arm_STRIP       := $(CROSS_PREFIX)strip
Linux-arm_CCFLAGS     := -I$(JAVA_HOME)/include -Ilib/inc_linux -Os -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIC -mfloat-abi=soft -fvisibility=hidden
Linux-arm_LINKFLAGS   := $(Default_LINKFLAGS)
Linux-arm_LIBNAME     := libsqlitejdbc.so
Linux-arm_SQLITE_FLAGS  :=

Windows-x86_64_CC           := $(CROSS_PREFIX)gcc
Windows-x86_64_STRIP        := $(CROSS_PREFIX)strip
Windows-x86_64_CCFLAGS      := -D_JNI_IMPLEMENTATION_ -Ilib/inc_win -Os
Windows-x86_64_LINKFLAGS    := -Wl,--kill-at -shared -static-libgcc
Windows-x86_64_LIBNAME      := sqlitejdbc.dll
Windows-x86_64_SQLITE_FLAGS :=


Linux-Android-arm_CC        := $(CROSS_PREFIX)clang
Linux-Android-arm_STRIP     := $(CROSS_ROOT)/bin/llvm-strip
Linux-Android-arm_CCFLAGS   := -I$(JAVA_HOME)/include -Ilib/inc_linux -I$(CROSS_ROOT)/sysroot/usr/include -Os -g -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIC -lm -lc -landroid -ldl -llog
Linux-Android-arm_LINKFLAGS := $(Default_LINKFLAGS) -Wl,-soname,libsqlitejdbc.so
Linux-Android-arm_LIBNAME   := libsqlitejdbc.so
Linux-Android-arm_SQLITE_FLAGS  :=

Linux-Android-aarch64_CC        := $(CROSS_PREFIX)clang
Linux-Android-aarch64_STRIP     := $(CROSS_ROOT)/bin/llvm-strip
Linux-Android-aarch64_CCFLAGS   := -I$(JAVA_HOME)/include -Ilib/inc_linux -I$(CROSS_ROOT)/sysroot/usr/include -Os -g -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIC -lm -lc -landroid -ldl -llog
Linux-Android-aarch64_LINKFLAGS := $(Default_LINKFLAGS) -Wl,-soname,libsqlitejdbc.so
Linux-Android-aarch64_LIBNAME   := libsqlitejdbc.so
Linux-Android-aarch64_SQLITE_FLAGS  :=

Linux-Android-x86_CC        := $(CROSS_PREFIX)clang
Linux-Android-x86_STRIP     := $(CROSS_ROOT)/bin/llvm-strip
Linux-Android-x86_CCFLAGS   := -I$(JAVA_HOME)/include -Ilib/inc_linux -I$(CROSS_ROOT)/sysroot/usr/include -Os -g -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIC -lm -lc -landroid -ldl -llog
Linux-Android-x86_LINKFLAGS := $(Default_LINKFLAGS) -Wl,-soname,libsqlitejdbc.so
Linux-Android-x86_LIBNAME   := libsqlitejdbc.so
Linux-Android-x86_SQLITE_FLAGS  :=

Linux-Android-x86_64_CC        := $(CROSS_PREFIX)clang
Linux-Android-x86_64_STRIP     := $(CROSS_ROOT)/bin/llvm-strip
Linux-Android-x86_64_CCFLAGS   := -I$(JAVA_HOME)/include -Ilib/inc_linux -I$(CROSS_ROOT)/sysroot/usr/include -Os -g -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIC -lm -lc -landroid -ldl -llog
Linux-Android-x86_64_LINKFLAGS := $(Default_LINKFLAGS) -Wl,-soname,libsqlitejdbc.so
Linux-Android-x86_64_LIBNAME   := libsqlitejdbc.so
Linux-Android-x86_64_SQLITE_FLAGS  :=

Mac-x86_64_CC        := gcc -arch $(OS_ARCH) 
Mac-x86_64_STRIP     := strip -x
MAC_SDK := /Developer/SDKs/MacOSX10.10.sdk
ifeq ($(wildcard MAC_SDK),)
	MAC_SDK := /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
endif
Mac-x86_64_CCFLAGS    := -I$(MAC_SDK)/System/Library/Frameworks/JavaVM.framework/Headers -Ilib/inc_mac -Os -fPIC -mmacosx-version-min=10.6 -fvisibility=hidden -Wno-implicit-function-declaration
Mac-x86_64_LINKFLAGS := -dynamiclib 
Mac-x86_64_LIBNAME   := libsqlitejdbc.dylib
Mac-x86_64_SQLITE_FLAGS  := 

# Use a CROSS_PREFIX as the cross-triple clang is not available in crossbuild, see https://github.com/multiarch/crossbuild/blob/ad79cc84b6fb3fb1d09bc4a78719ef26f23bab85/Dockerfile#L134
# When running on a M1 mac, CROSS_PREFIX will be empty, and 'make native' can still build
Mac-aarch64_CC        := $(CROSS_PREFIX)clang
Mac-aarch64_STRIP     := $(CROSS_PREFIX)strip -x
MAC_SDK := /usr/osxcross/SDK/MacOSX11.3.sdk
Mac-aarch64_CCFLAGS    := -I$(MAC_SDK)/System/Library/Frameworks/JavaVM.framework/Headers -Ilib/inc_mac -Os -fPIC -mmacosx-version-min=10.9 -fvisibility=hidden -Wno-implicit-function-declaration
Mac-aarch64_LINKFLAGS  := -dynamiclib
Mac-aarch64_LIBNAME    := libsqlitejdbc.dylib
Mac-aarch64_SQLITE_FLAGS := 

CC        := $($(target)_CC)
STRIP     := $($(target)_STRIP)
CCFLAGS   := $($(target)_CCFLAGS) 
LINKFLAGS := $($(target)_LINKFLAGS) 
LIBNAME   := $($(target)_LIBNAME)
SQLITE_FLAGS := $($(target)_SQLITE_FLAGS)
CCFLAGS := $(CCFLAGS) 
ifneq ($(jni_include),)
CCFLAGS := $(CCFLAGS) -I"$(jni_include)"
endif
ifneq ($(jni_md_include),)
CCFLAGS := $(CCFLAGS) -I"$(jni_md_include)"
endif

