name: maven_artefact
on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:

  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5

    - name: Install system packages
      run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          zipalign \
          apksigner

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: build maven artifact
      run: |
        ./tools/make_aar_and_maven.sh

    - name: Rename artifact for nightly upload
      run: |
        cp -av ./example_android/stub_work/local_maven_androidjdbc_*.zip ./

    - name: Upload to nightly release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/android_test'
      with:
        allowUpdates: true
        tag: nightly
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        prerelease: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "local_maven_androidjdbc*.zip"

    - name: GitHub info
      run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME" || echo "NO ERR"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}" || echo "NO ERR"
         echo "Tag name from github.ref: ${{  github.ref }}" || echo "NO ERR"

    - name: Upload to versioned release
      if: contains(github.ref, 'refs/tags/jdbcjni')
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "local_maven_androidjdbc*.zip"
