name: example_with_gradle
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: run with gradle
        run: |
          cd example_gradle_linux/
          ./gradlew run

      - name: show beginning of the DB file
        run: |
          cd example_gradle_linux/
          cat app/sample.db|hexdump -C|head -24

      - name: check if DB is really encrypted
        shell: bash
        run: |
          cd example_gradle_linux/
          err=$(cat app/sample.db|hexdump -C|head -24|grep "SQLite")
          if [ "$err""x" != "x" ]; then
            echo "Database may not be encrypted !"
            exit 1
          fi


  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Display the path
        run: echo %PATH%
        shell: cmd

      - name: java-version
        run: java -version
        shell: bash

      - name: run with gradle
        shell: bash
        run: |
          cd example_gradle_linux/
          ./gradlew run

      - name: show beginning of the DB file
        shell: bash
        run: |
          cd example_gradle_linux/
          cat app/sample.db|xxd|head -24

      - name: check if DB is really encrypted
        shell: bash
        run: |
          cd example_gradle_linux/
          err=$(cat app/sample.db|xxd|head -24|grep "SQLite")
          if [ "$err""x" != "x" ]; then
            echo "Database may not be encrypted !"
            exit 1
          fi

